services:
  web:
    build: ./web
    ports:
      - "80:80"
    volumes:
      - ./web:/app
    environment:
      API_URL: "http://backend:8081"
      BACKEND_SERVER: "http://backend:8081"
    depends_on:
      - backend
    networks:
      - mynet

  backend:
    build: ./backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
    environment:
      HOST: "0.0.0.0"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    depends_on:
      - db
    networks:
      - mynet

  db:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /data/redis-data:/data
    networks:
      - mynet

networks:
  mynet:
    driver: bridge